// ============================================================
// 构建后生成 dist/feed.xml
// ------------------------------------------------------------
// 基于 src/data/profile.js 和 src/data/posts.js 自动生成 RSS 2.0 订阅源。
// 只包含已发布文章（published !== false）。
// 用法：node scripts/gen-rss.mjs
// 可选环境变量 RSS_SITE_URL 覆盖站点根地址，如 https://example.com/
// ============================================================
import { writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')

const { profile } = await import(pathToFileURL(resolve(root, 'src/data/profile.js')).href)
const { posts } = await import(pathToFileURL(resolve(root, 'src/data/posts.js')).href)

// 站点根地址
let siteUrl = (process.env.RSS_SITE_URL || '').trim()
if (!siteUrl && profile.contact?.github) {
  const m = profile.contact.github.match(/github\.com\/([^/]+)/)
  if (m) siteUrl = `https://${m[1]}.github.io`
}
if (!siteUrl) {
  siteUrl = './'
  console.warn('[gen-rss] RSS_SITE_URL 未设置且无法从 GitHub 链接推断，链接使用相对路径 ./')
}
siteUrl = siteUrl.replace(/\/$/, '') + '/'

function escapeXml(str) {
  return String(str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

function toRfc822Date(isoDateStr) {
  const d = new Date(isoDateStr + 'T00:00:00')
  if (isNaN(d.getTime())) return new Date().toUTCString()
  return d.toUTCString()
}

function stripMarkdown(md) {
  return String(md || '')
    // 代码块
    .replace(/```[\s\S]*?```/g, ' ')
    // 行内代码
    .replace(/`[^`]+`/g, ' ')
    // 加粗 / 斜体
    .replace(/\*\*?([^*]+)\*\*?/g, '$1')
    // 标题
    .replace(/#{1,6}\s+/g, '')
    // 链接 [text](url)
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    // 图片 ![alt](url)
    .replace(/!\[([^\]]*)\]\([^)]+\)/g, ' ')
    // 引用、列表符号
    .replace(/^[>\-*+]\s+/gm, '')
    // 多余空白
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 300)
}

const now = new Date().toUTCString()
const feedTitle = escapeXml(profile.site?.title || profile.name || 'Blog')
const feedDesc = escapeXml(profile.site?.description || profile.tagline || '')
const feedLang = 'zh-CN'
const authorEmail = escapeXml(profile.contact?.email || '')

const published = (posts || []).filter((p) => p.published !== false).sort((a, b) => (a.date < b.date ? 1 : -1))

let xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- RSS 2.0 generated by gen-rss.mjs -->
<!-- Spec: https://www.rssboard.org/rss-specification -->
`

xml += `<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>${feedTitle}</title>
    <link>${siteUrl}</link>
    <description>${feedDesc}</description>
    <language>${feedLang}</language>
    <lastBuildDate>${now}</lastBuildDate>
    <generator>RSS for Node</generator>
    <atom:link href="${siteUrl}feed.xml" rel="self" type="application/rss+xml" />
`

if (authorEmail) {
  xml += `    <managingEditor>${authorEmail}</managingEditor>
    <webMaster>${authorEmail}</webMaster>
`
}

for (const post of published) {
  const postUrl = `${siteUrl}#/post/${post.id}`
  const pubDate = toRfc822Date(post.date)
  const desc = escapeXml(stripMarkdown(post.summary || post.content || ''))

  xml += `    <item>
      <title>${escapeXml(post.title)}</title>
      <link>${postUrl}</link>
      <guid isPermaLink="true">${postUrl}</guid>
      <pubDate>${pubDate}</pubDate>
      <description>${desc}</description>
      <category>${escapeXml(post.category)}</category>
`
  if (post.tags && Array.isArray(post.tags)) {
    for (const tag of post.tags) {
      xml += `      <category>${escapeXml(tag)}</category>
`
    }
  }
  xml += `    </item>
`
}

xml += `  </channel>
</rss>
`

const distDir = resolve(root, 'dist')
mkdirSync(distDir, { recursive: true })
const file = resolve(distDir, 'feed.xml')
writeFileSync(file, xml, 'utf-8')
console.log(`[gen-rss] written: ${file} (${published.length} items)`)
